[project]
name = "nef-file-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "exif>=1.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
