[project]
name = "nef-file-manager"
version = "0.1.0"
description = "Move Nikon RAW files (NEF) imported from NX Studio to an organized format YYYY/YYYY-MM-DD"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

